---
- name: Install OSX applications
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - docker
      - firefox
      - iterm2
      - lastpass
      - slack
      - spotify
      - vlc
      - visual-studio-code

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when: not homebrew_check.stat.exists

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: true
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
        accept_external_apps: true
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
