---
- name: Install OSX Packages
  hosts: localhost
  become: false
  vars:
    brew_packages:
        - libpq
        - bash-completion
        - docker-compose
        - docker-machine
        - go
        - jq
        - nmap
        - pyenv
        - terraform
        - terraform-inventory
        - terraform-provisioner-ansible

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when: not homebrew_check.stat.exists

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: true
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
    
    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      when: homebrew_check.stat.exists
